replicaCount: 1

namespace: sige-test-devops

image:
  repository: hoppscotch/hoppscotch-backend
  tag: latest
  pullPolicy: Always
  pullSecret: # regcred

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  containerPort: 3170

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: backend-hoppscotch.sige-test.com
      paths: ["/"]
  tls:
    - secretName: sige-test.com-tls-secret
      hosts:
        - backend-hoppscotch.sige-test.com

extra_labels:
  exposed-by-ingress: 'true'

resources:
  limits:
    cpu: 1
    memory: 1536Mi
  requests:
    cpu: 500m
    memory: 1536Mi

probes:
  readinessProbe_path: /ping
  readinessProbe_type: httpGet
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 20

  livenessProbe_type: httpGet
  livenessProbe_path: /ping
  livenessProbe:
    initialDelaySeconds: 100
    periodSeconds: 30
    failureThreshold: 10
