apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hoppscotch.fullname" . }}-migration
  namespace: {{ .Values.namespace }}
  labels:
{{ include "hoppscotch.labels" . | indent 4 }}
{{ include "hoppscotch.extra_labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "0"
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}-migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: {{- include "env-backend" . | nindent 12 }}
          command:
            - "/bin/sh"
            - "-c"
            - |
              pnpx prisma migrate deploy
      restartPolicy: OnFailure
