apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hoppscotch.fullname" . }}-migration
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "-1"
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}-migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/bin/sh"
            - "-c"
            - |
              pnpx prisma migrate deploy
          env:
            {{- include "env" . | nindent 12 }}
      restartPolicy: OnFailure
