apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hoppscotch.fullname" . }}-migration
  namespace: {{ .Values.namespace }}
  labels:
{{ include "hoppscotch.labels" . | indent 4 }}
{{ include "hoppscotch.extra_labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "3"
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}-migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: {{- include "env-backend" . | nindent 12 }}
          command:
            - "/bin/sh"
            - "-c"
            - |
              apk add curl;

              until curl --silent -X GET http://{{ template "hoppscotch.fullname" . }}:3170; do echo "Waiting for backend service..."; sleep 5; done;

              pnpx prisma migrate deploy

              echo "Backend Service is ready. Migrations are completed."
      restartPolicy: OnFailure
