---
# Source: hoppscotch/charts/admin/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: admin-db
  namespace: sige-test-devops
  labels:
    app.kubernetes.io/name: admin
    helm.sh/chart: admin-0.4.0
    app.kubernetes.io/instance: db
    app.kubernetes.io/version: "2023.8.2"
    app.kubernetes.io/managed-by: Helm
    
    exposed-by-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: admin
    app.kubernetes.io/instance: db
---
# Source: hoppscotch/charts/application/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: application-db
  namespace: sige-test-devops
  labels:
    app.kubernetes.io/name: application
    helm.sh/chart: application-0.4.0
    app.kubernetes.io/instance: db
    app.kubernetes.io/version: "2023.8.2"
    app.kubernetes.io/managed-by: Helm
    
    exposed-by-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP

  selector:
    app.kubernetes.io/name: application
    app.kubernetes.io/instance: db
---
# Source: hoppscotch/charts/backend/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-db
  namespace: sige-test-devops
  labels:
    app.kubernetes.io/name: backend
    helm.sh/chart: backend-0.4.0
    app.kubernetes.io/instance: db
    app.kubernetes.io/version: "2023.8.2"
    app.kubernetes.io/managed-by: Helm
    
    exposed-by-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3170
      protocol: TCP
  selector:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: db
---
# Source: hoppscotch/charts/admin/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-db
  namespace: sige-test-devops
  labels:
    app.kubernetes.io/name: admin
    helm.sh/chart: admin-0.4.0
    app.kubernetes.io/instance: db
    app.kubernetes.io/version: "2023.8.2"
    app.kubernetes.io/managed-by: Helm
    
    exposed-by-ingress: "true"
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
      - "admin-hoppscotch.sige-test.com"
    secretName: sige-test.com-tls-secret
  rules:
  - host: "admin-hoppscotch.sige-test.com"
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: admin-db
              port:
                number: 8080
---
# Source: hoppscotch/charts/application/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: application-db
  namespace: sige-test-devops
  labels:
    app.kubernetes.io/name: application
    helm.sh/chart: application-0.4.0
    app.kubernetes.io/instance: db
    app.kubernetes.io/version: "2023.8.2"
    app.kubernetes.io/managed-by: Helm
    
    exposed-by-ingress: "true"
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
      - "app-hoppscotch.sige-test.com"
    secretName: sige-test.com-tls-secret
  rules:
  - host: "app-hoppscotch.sige-test.com"
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: application-db
              port:
                number: 8080
---
# Source: hoppscotch/charts/backend/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-db
  namespace: sige-test-devops
  labels:
    app.kubernetes.io/name: backend
    helm.sh/chart: backend-0.4.0
    app.kubernetes.io/instance: db
    app.kubernetes.io/version: "2023.8.2"
    app.kubernetes.io/managed-by: Helm
    
    exposed-by-ingress: "true"
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
      - "backend-hoppscotch.sige-test.com"
    secretName: sige-test.com-tls-secret
  rules:
  - host: "backend-hoppscotch.sige-test.com"
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: backend-db
              port:
                number: 3170
---
# Source: hoppscotch/charts/application/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-db
  namespace: sige-test-devops
  labels:
    app.kubernetes.io/name: application
    helm.sh/chart: application-0.4.0
    app.kubernetes.io/instance: db
    app.kubernetes.io/version: "2023.8.2"
    app.kubernetes.io/managed-by: Helm
    
    exposed-by-ingress: "true"
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: application
      app.kubernetes.io/instance: db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: application
        app.kubernetes.io/instance: db
        
        exposed-by-ingress: "true"
    spec:
      containers:
        - name: application
          image: "hoppscotch/hoppscotch-frontend:latest"
          imagePullPolicy: Always
          env:
            - name: VITE_ALLOWED_AUTH_PROVIDERS
              value: GOOGLE,GITHUB,MICROSOFT,EMAIL
            - name: VITE_BASE_URL
              value: http://app-hoppscotch.sige-test.com
            - name: VITE_SHORTCODE_BASE_URL
              value: http://app-hoppscotch.sige-test.com
            - name: VITE_ADMIN_URL
              value: http://admin-hoppscotch.sige-test.com
            - name: VITE_BACKEND_GQL_URL
              value: http://backend-hoppscotch.sige-test.com/graphql
            - name: VITE_BACKEND_WS_URL
              value: ws://backend-hoppscotch.sige-test.com/graphql
            - name: VITE_BACKEND_API_URL
              value: http://backend-hoppscotch.sige-test.com/v1
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            failureThreshold: 15
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            failureThreshold: 10
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
# Source: hoppscotch/charts/backend/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-db
  namespace: sige-test-devops
  labels:
    app.kubernetes.io/name: backend
    helm.sh/chart: backend-0.4.0
    app.kubernetes.io/instance: db
    app.kubernetes.io/version: "2023.8.2"
    app.kubernetes.io/managed-by: Helm
    
    exposed-by-ingress: "true"
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
      app.kubernetes.io/instance: db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
        app.kubernetes.io/instance: db
        
        exposed-by-ingress: "true"
    spec:
      containers:
        - name: backend
          image: "hoppscotch/hoppscotch-backend:latest"
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              value: "postgresql://db:password@sige-basic-postgresql.sige-test.com:5432/db"
            - name: MAGIC_LINK_TOKEN_VALIDITY
              value: "3"
            - name: JWT_SECRET
              value: 'secret12333'
            - name: TOKEN_SALT_COMPLEXITY
              value: '10'
            - name: REFRESH_TOKEN_VALIDITY
              value: '604800000'
            - name: ACCESS_TOKEN_VALIDITY
              value: '86400000'
            - name: SESSION_SECRET
              value: 'anothersecretcode123'
            - name: REDIRECT_URL
              value: 'http://localhost:3000'
            - name: WHITELISTED_ORIGINS
              value: "http://localhost:3170,http://localhost:3000,http://localhost:3100"
            - name: VITE_ALLOWED_AUTH_PROVIDERS
              value: GOOGLE,GITHUB,MICROSOFT,EMAIL
            - name: GOOGLE_CLIENT_ID
              value: "*******************"
            - name: GOOGLE_CLIENT_SECRET
              value: "*******************"
            - name: GOOGLE_CALLBACK_URL
              value: "http://localhost:3170/v1/auth/google/callback"
            - name: GOOGLE_SCOPE
              value: "email, profile"
            - name: GITHUB_CLIENT_ID
              value: =Ov23ct9onMzNbOMFVxmy
            - name: GITHUB_CLIENT_SECRET
              value: c2ca2c437c7df7e6b5d914670dfcc6f73b54d849
            - name: GITHUB_CALLBACK_URL
              value: "http://localhost:3170/v1/auth/github/callback"
            - name: GITHUB_SCOPE
              value: "user:email"
            - name: MAILER_SMTP_URL
              value: "smtp://host.docker.internal:1025"
            - name: MAILER_ADDRESS_FROM
              value: '"From Name Here" <yopjason@gmail.com>'
            - name: RATE_LIMIT_TTL
              value: '60'
            - name: RATE_LIMIT_MAX
              value: '100'
            - name: VITE_BASE_URL
              value: http://app-hoppscotch.sige-test.com
            - name: VITE_SHORTCODE_BASE_URL
              value: http://app-hoppscotch.sige-test.com
            - name: VITE_ADMIN_URL
              value: http://admin-hoppscotch.sige-test.com
            - name: VITE_BACKEND_GQL_URL
              value: http://backend-hoppscotch.sige-test.com/graphql
            - name: VITE_BACKEND_WS_URL
              value: ws://backend-hoppscotch.sige-test.com/graphql
            - name: VITE_BACKEND_API_URL
              value: http://backend-hoppscotch.sige-test.com/v1
          ports:
            - name: http
              containerPort: 3170
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ping
              port: 3170
            failureThreshold: 20
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /ping
              port: 3170
            failureThreshold: 10
            initialDelaySeconds: 100
            periodSeconds: 30
          resources:
            limits:
              cpu: 1
              memory: 1536Mi
            requests:
              cpu: 500m
              memory: 1536Mi
---
# Source: hoppscotch/charts/backend/templates/init-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: backend-db-migration
  namespace: sige-test-devops
  labels:
    app.kubernetes.io/name: backend
    helm.sh/chart: backend-0.4.0
    app.kubernetes.io/instance: db
    app.kubernetes.io/version: "2023.8.2"
    app.kubernetes.io/managed-by: Helm
    
    exposed-by-ingress: "true"
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: backend-migration
          image: "hoppscotch/hoppscotch-backend:latest"
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              value: "postgresql://db:password@sige-basic-postgresql.sige-test.com:5432/db"
            - name: MAGIC_LINK_TOKEN_VALIDITY
              value: "3"
            - name: JWT_SECRET
              value: 'secret12333'
            - name: TOKEN_SALT_COMPLEXITY
              value: '10'
            - name: REFRESH_TOKEN_VALIDITY
              value: '604800000'
            - name: ACCESS_TOKEN_VALIDITY
              value: '86400000'
            - name: SESSION_SECRET
              value: 'anothersecretcode123'
            - name: REDIRECT_URL
              value: 'http://localhost:3000'
            - name: WHITELISTED_ORIGINS
              value: "http://localhost:3170,http://localhost:3000,http://localhost:3100"
            - name: VITE_ALLOWED_AUTH_PROVIDERS
              value: GOOGLE,GITHUB,MICROSOFT,EMAIL
            - name: GOOGLE_CLIENT_ID
              value: "*******************"
            - name: GOOGLE_CLIENT_SECRET
              value: "*******************"
            - name: GOOGLE_CALLBACK_URL
              value: "http://localhost:3170/v1/auth/google/callback"
            - name: GOOGLE_SCOPE
              value: "email, profile"
            - name: GITHUB_CLIENT_ID
              value: =Ov23ct9onMzNbOMFVxmy
            - name: GITHUB_CLIENT_SECRET
              value: c2ca2c437c7df7e6b5d914670dfcc6f73b54d849
            - name: GITHUB_CALLBACK_URL
              value: "http://localhost:3170/v1/auth/github/callback"
            - name: GITHUB_SCOPE
              value: "user:email"
            - name: MAILER_SMTP_URL
              value: "smtp://host.docker.internal:1025"
            - name: MAILER_ADDRESS_FROM
              value: '"From Name Here" <yopjason@gmail.com>'
            - name: RATE_LIMIT_TTL
              value: '60'
            - name: RATE_LIMIT_MAX
              value: '100'
            - name: VITE_BASE_URL
              value: http://app-hoppscotch.sige-test.com
            - name: VITE_SHORTCODE_BASE_URL
              value: http://app-hoppscotch.sige-test.com
            - name: VITE_ADMIN_URL
              value: http://admin-hoppscotch.sige-test.com
            - name: VITE_BACKEND_GQL_URL
              value: http://backend-hoppscotch.sige-test.com/graphql
            - name: VITE_BACKEND_WS_URL
              value: ws://backend-hoppscotch.sige-test.com/graphql
            - name: VITE_BACKEND_API_URL
              value: http://backend-hoppscotch.sige-test.com/v1
          command:
            - "/bin/sh"
            - "-c"
            - |
              pnpx prisma migrate deploy
      restartPolicy: OnFailure
---
# Source: hoppscotch/charts/admin/templates/deployment.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-db
  namespace: 
  labels:
    app.kubernetes.io/name: admin
    helm.sh/chart: admin-0.4.0
    app.kubernetes.io/instance: db
    app.kubernetes.io/version: "2023.8.2"
    app.kubernetes.io/managed-by: Helm
    
    exposed-by-ingress: "true"
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "1"
spec:
  tls:
  - hosts:
      - "admin-hoppscotch.sige-test.com"
    secretName: sige-test.com-tls-secret
  rules:
  - host: "admin-hoppscotch.sige-test.com"
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: admin-db
              port:
                number: 8080
